// <auto-generated />
using System;
using Garage2._0_Group5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage2._0_Group5.Migrations
{
    [DbContext(typeof(Garage2_0_Group5Context))]
    [Migration("20231106145231_Seed2")]
    partial class Seed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage2._0_Group5.Models.Entities.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("TimeAtCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeAtCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleBrand")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegistrationNumber = "",
                            TimeAtCheckIn = new DateTime(2023, 11, 6, 14, 52, 31, 142, DateTimeKind.Utc).AddTicks(2052),
                            VehicleBrand = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            RegistrationNumber = "",
                            TimeAtCheckIn = new DateTime(2023, 11, 6, 14, 52, 31, 142, DateTimeKind.Utc).AddTicks(2056),
                            VehicleBrand = 1,
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 3,
                            RegistrationNumber = "",
                            TimeAtCheckIn = new DateTime(2023, 11, 6, 14, 52, 31, 142, DateTimeKind.Utc).AddTicks(2057),
                            VehicleBrand = 2,
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 4,
                            RegistrationNumber = "",
                            TimeAtCheckIn = new DateTime(2023, 11, 6, 14, 52, 31, 142, DateTimeKind.Utc).AddTicks(2058),
                            VehicleBrand = 3,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 5,
                            RegistrationNumber = "",
                            TimeAtCheckIn = new DateTime(2023, 11, 6, 14, 52, 31, 142, DateTimeKind.Utc).AddTicks(2059),
                            VehicleBrand = 4,
                            VehicleType = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
